ilcardella/TradingBot

config/config.json, scripts/main.py
=> Add management of log file 

config/config.json, scripts/Strategies/FAIG_iqr.py, scripts/Strategies/SimpleMACD.py, scripts/Strategies/Strategy.py
called in constructor and implemented in concrete subclasses
Closes #3
=> Add abstract method read_configuration to Strategy class,

config/config.json, scripts/main.py
Change default log location to home dir
Closes #22
=> Allow home dir as location for the log file

scripts/IGInterface.py, scripts/Strategies/Strategy.py
=> Close positions

scripts/Strategies/Strategy.py
=> Close positions checks

README.md, scripts/Strategies/SimpleMACD.py, scripts/Utils.py
=> SimpleMACD wait for next market opening before spinning again

requirements.txt, scripts/Interfaces/IGInterface.py, test/test_data/mock_ig_account_details.json, test/test_data/mock_ig_login.json, test/test_data/mock_ig_positions.json, test/test_data/mock_ig_set_account.json, test/test_ig_interface.py
=> Refactor ig

README.md, config/config.json, doc/source/system.rst, src/Strategies/FAIG_iqr.py, src/Strategies/Strategy.py, src/Strategies/StrategyFactory.py, src/TradingBot.py, test/test_strategy_factory.py
=> Strategy configurable

README.md, doc/conf.py, doc/source/modules.rst, doc/source/system.rst, src/Interfaces/AVInterface.py, src/Interfaces/Broker.py, src/Interfaces/IGInterface.py, src/Strategies/SimpleMACD.py, src/Strategies/Strategy.py, src/Strategies/StrategyFactory.py, src/Strategies/WeightedAvgPeak.py, src/TradingBot.py, test/common/MockComponents.py, test/test_ig_interface.py, test/test_simple_macd.py, test/test_strategy_factory.py, test/test_weighted_avg_peak.py, trading_bot_ctl
=> Broker template

README.md, config/config.json, src/Interfaces/AVInterface.py, src/Interfaces/Broker.py, src/Strategies/SimpleMACD.py, src/TradingBot.py, src/Utils.py, test/common/MockComponents.py, test/test_simple_macd.py, test/test_weighted_avg_peak.py, trading_bot_ctl
=> Av timeout

src/Interfaces/AVInterface.py, src/Interfaces/Broker.py, src/Interfaces/IGInterface.py, src/Strategies/SimpleMACD.py, src/Strategies/WeightedAvgPeak.py, test/common/MockComponents.py, test/test_simple_macd.py
=> Av quote endpoint

README.md, config/config.json, requirements.txt, run_docker.sh, src/Interfaces/AVInterface.py, src/Interfaces/Broker.py, src/TradingBot.py, src/Utils.py, trading_bot_ctl
=> Av retries

src/TradingBot.py, trading_bot.py
=> Added check on sphinx before building docs

CHANGELOG.md, doc/index.rst, doc/source/modules.rst, doc/source/system.rst
Fixed sphinx documentation titles
=> Correct doc titles

README.md, config/config.json, doc/source/modules.rst, doc/source/system.rst, src/Components/TimeProvider.py, src/Strategies/SimpleMACD.py, src/Strategies/Strategy.py, src/Strategies/WeightedAvgPeak.py, src/TradingBot.py, src/Utility/Utils.py, test/test_time_provider.py, test/test_trading_bot.py, test/test_utils.py
=> Add time provider

src/TradingBot.py, test/test_data/config.json, test/test_data/credentials.json, test/test_trading_bot.py
=> config file is injected in TradingBot init

setup.py
Add setup.py to install package using setuptools
Closes #47
May help with #160
=> Make python package

.travis.yml
CI builds the docker image too
=> Added docker image build in ci

Dockerfile, src/Components/MarketProvider.py, src/TradingBot.py
=> Added support for epic optional argument

CHANGELOG.md, src/Components/Broker/AVInterface.py, src/Components/Broker/AbstractInterfaces.py, src/Components/Broker/IGInterface.py, src/Components/Broker/YFinanceInterface.py, src/Strategies/SimpleMACD.py, src/TradingBot.py, test/test_data/config.json, test/test_simple_macd.py, test/test_trading_bot.py
Resolves some bugs after the big refactoring
=> Resolve bug after refactoring of components

CHANGELOG.md, tradingbot/components/broker/ig_interface.py
=> Fixed security warning in ig_interface.py logging

CHANGELOG.md, tradingbot/__init__.py
=> Removed default value for --config optional argument
